# ARGUMENTS --------------------------------------------------------------------
##
# Base Container version
# Using Flutter v3.27.x
##
ARG SDK_BASE_VERSION=SDK
##
# Base container version
##
ARG BASE_VERSION=runtime_debug

##
# Board architecture
##
ARG IMAGE_ARCH=

##
# Directory of the application inside container
##s
ARG APP_ROOT=

##
# Debug port
##
ARG DEBUG_SSH_PORT=

##
# Run as
##
ARG SSHUSERNAME=

# BUILD/DEPLOY -----------------------------------------------------------------------
##
# Build/Deploy Step
##
FROM crossware.app:5050/public-repos/flutter:${SDK_BASE_VERSION} as build

ARG IMAGE_ARCH
ARG GPU
ARG APP_ROOT

COPY . ${APP_ROOT}
WORKDIR ${APP_ROOT}
RUN flutter-elinux clean; flutter-elinux pub get; flutter-elinux build elinux --debug

FROM crossware.app:5050/public-repos/flutter:${BASE_VERSION} as debug
ARG SSHUSERNAME
ARG DEBUG_SSH_PORT
ARG APP_ROOT

# SSH for remote debug
EXPOSE ${DEBUG_SSH_PORT}

WORKDIR ${APP_ROOT}

# Install debug required packages
RUN apt-get -q -y update && \
    apt-get -q -y install \
    openssl \
    openssh-server \
    rsync \
    file \
    curl \
    gdb \
    gdbserver \
    && \
    apt-get clean && apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# automate for torizonPackages.json
RUN apt-get -q -y update && \
apt-get -q -y install \
# DO NOT REMOVE THIS LABEL: this is used for VS Code automation
# __torizon_packages_dev_start__
# __torizon_packages_dev_end__
# DO NOT REMOVE THIS LABEL: this is used for VS Code automation
&& \
apt-get clean && apt-get autoremove && \
rm -rf /var/lib/apt/lists/*

# ⚠️ DEBUG PURPOSES ONLY!!
# THIS CONFIGURES AN INSECURE SSH CONNECTION

# create folders needed for the different components
# configures SSH access to the container and sets environment by default
RUN mkdir /var/run/sshd && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' \
        -i /etc/pam.d/sshd && \
    if test $SSHUSERNAME != root ; \
        then mkdir -p /home/$SSHUSERNAME/.ssh ; \
        else mkdir -p /root/.ssh ; fi && \
    echo "PermitUserEnvironment yes" >> /etc/ssh/sshd_config && \
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    echo "Port ${DEBUG_SSH_PORT}" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config && \
    su -c "env" $SSHUSERNAME > /etc/environment && \
    echo "$SSHUSERNAME:" | chpasswd -e

RUN rm -r /etc/ssh/ssh*key && \
    dpkg-reconfigure openssh-server

COPY --chown=torizon:torizon run.sh ${APP_ROOT}/

COPY --from=build ${APP_ROOT}/build/elinux/arm64/debug/bundle/ ${APP_ROOT}/bundle
RUN cp ${APP_ROOT}/bundle/sample ${APP_ROOT}/

WORKDIR ${APP_ROOT}

ENV FLUTTER_DRM_DEVICE="/dev/dri/card0:/dev/dri/card1"
ENV APP_PATH=${APP_ROOT}/bundle
RUN chmod +x ${APP_ROOT}/run.sh
ENV RUNTIME debug
CMD ["/home/torizon/app/run.sh"]
# BUILD/DEPLOY -----------------------------------------------------------------------
