version: "3.9"
services:
    __container__-debug:
        build:
            context: .
            dockerfile: Dockerfile.debug
        image: ${LOCAL_REGISTRY}:5002/__container__-debug:${TAG}
        ports:
            - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
        volumes:
            - type: bind
              source: /dev
              target: /dev
        # Add device access rights through cgroup...
        device_cgroup_rules:
          # ... for tty
          - "c 4:* rmw"
          # ... for /dev/input devices
          - "c 13:* rmw"
          # ... for /dev/dri devices
          - "c 226:* rmw"
          - "c 199:* rmw"
          # ... for /dev/fb0
          - "c 29:* rmw"

    __container__:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${DOCKER_LOGIN}/__container__:${TAG}
        volumes:
            - type: bind
              source: /dev
              target: /dev
        # Add device access rights through cgroup...
        device_cgroup_rules:
          # ... for tty
          - "c 4:* rmw"
          # ... for /dev/input devices
          - "c 13:* rmw"
          # ... for /dev/dri devices
          - "c 226:* rmw"
          - "c 199:* rmw"
          # ... for /dev/fb0
          - "c 29:* rmw"
